version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Map backend container's port 5000 to host port 5000
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:5000  # Internal service name used in Compose network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Map frontend container's port 80 to host port 80
    networks:
      - app-network
    environment:
      - VITE_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

 
networks:
  app-network:
    driver: bridge
