version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Map backend container's port 5000 to host port 5000
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data  # Mount host directory to backend's CSV path

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"  # Map frontend container's port 80 to host port 80
    networks:
      - app-network
    environment:
      - VITE_APP_API_URL=http://backend:5000
    depends_on:
      - backend
 
networks:
  app-network:
    driver: bridge
